Traceback (most recent call last):
  File "D:\programas\Anaconda\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\programas\Anaconda\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programas\Anaconda\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programas\Anaconda\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programas\Anaconda\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\programas\Anaconda\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\programas\Anaconda\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\programas\Anaconda\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from qiskit import QuantumCircuit, assemble, Aer
from math import pi, sqrt
from qiskit.visualization import plot_bloch_multivector, plot_histogram
sim = Aer.get_backend('aer_simulator')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
File [1;32mD:\programas\Anaconda\Lib\site-packages\qiskit\__init__.py:123[0m, in [0;36mAerWrapper.__getattr__[1;34m(self, attr)[0m
[0;32m    122[0m [38;5;28;01mtry[39;00m:
[1;32m--> 123[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit[39;00m[38;5;21;01m.[39;00m[38;5;21;01mproviders[39;00m [38;5;28;01mimport[39;00m aer
[0;32m    125[0m     [38;5;28mself[39m[38;5;241m.[39maer [38;5;241m=[39m aer[38;5;241m.[39mAer

[1;31mImportError[0m: cannot import name 'aer' from 'qiskit.providers' (D:\programas\Anaconda\Lib\site-packages\qiskit\providers\__init__.py)

The above exception was the direct cause of the following exception:

[1;31mMissingOptionalLibraryError[0m               Traceback (most recent call last)
Cell [1;32mIn[1], line 4[0m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmath[39;00m [38;5;28;01mimport[39;00m pi, sqrt
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvisualization[39;00m [38;5;28;01mimport[39;00m plot_bloch_multivector, plot_histogram
[1;32m----> 4[0m sim [38;5;241m=[39m Aer[38;5;241m.[39mget_backend([38;5;124m'[39m[38;5;124maer_simulator[39m[38;5;124m'[39m)

File [1;32mD:\programas\Anaconda\Lib\site-packages\qiskit\__init__.py:134[0m, in [0;36mAerWrapper.__getattr__[1;34m(self, attr)[0m
[0;32m    126[0m         warnings[38;5;241m.[39mwarn(
[0;32m    127[0m             [38;5;124m"[39m[38;5;124mThe qiskit.Aer entry point will be deprecated in a future release and [39m[38;5;124m"[39m
[0;32m    128[0m             [38;5;124m"[39m[38;5;124msubsequently removed. Instead you should use this [39m[38;5;124m"[39m
[1;32m   (...)[0m
[0;32m    131[0m             stacklevel[38;5;241m=[39m[38;5;241m2[39m,
[0;32m    132[0m         )
[0;32m    133[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m ex:
[1;32m--> 134[0m         [38;5;28;01mraise[39;00m MissingOptionalLibraryError(
[0;32m    135[0m             [38;5;124m"[39m[38;5;124mqiskit-aer[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mAer provider[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mpip install qiskit-aer[39m[38;5;124m"[39m
[0;32m    136[0m         ) [38;5;28;01mfrom[39;00m [38;5;21;01mex[39;00m
[0;32m    137[0m [38;5;28;01mreturn[39;00m [38;5;28mgetattr[39m([38;5;28mself[39m[38;5;241m.[39maer, attr)

[1;31mMissingOptionalLibraryError[0m: "The 'qiskit-aer' library is required to use 'Aer provider'. You can install it with 'pip install qiskit-aer'."
MissingOptionalLibraryError: "The 'qiskit-aer' library is required to use 'Aer provider'. You can install it with 'pip install qiskit-aer'."

